### ISSUE TITLE
Initing new project on Windows 10

### ISSUE THREAD

**Issue by mirus-ua** [jetli/create-yew-app#16]
Hi. When I try to create a new project with `npx create-yew app name` or `yarn create yew-app name` I got this error.

```
> npx create-yew-app test1

 Creating a new Yew app in<path_to_folder>\test1.

 � Rust + � WebAssembly + Yew = ❤️

 Installing dependencies...
C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\create-yew-app\createYewApp.js:27
    throw output.error;
    ^

Error: spawnSync npm ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:616:24)
    at run (C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\create-yew-app\createYewApp.js:24:18)
    at C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\create-yew-app\createYewApp.js:83:5
    at C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\cpr\lib\index.js:294:33
    at check (C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\cpr\lib\index.js:190:17)
    at copy (C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\cpr\lib\index.js:198:24)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ 'install' ]
}

```

Windows 10 2004 19041.630
rustc 1.43.1 (8d69840ab 2020-05-04)
cargo 1.43.0 (2cbe9048e 2020-05-03)
node v12.16.3

**Comment by jetli** [comment]
Published a new version to npm, please try again.
