### ISSUE TITLE
Fails to install `wasm-pack`

### ISSUE THREAD

**Issue by lord-ne** [jetli/create-yew-app#22]
I get the following error message when creating a new app:

```
Error: Bad error code when running `cargo install wasm-pack`: 101
    at run (C:\Users\Noam\AppData\Local\npm-cache\_npx\432d571bf15e5fbf\node_modules\create-yew-app\createYewApp.js:32:11)
    at C:\Users\Noam\AppData\Local\npm-cache\_npx\432d571bf15e5fbf\node_modules\create-yew-app\createYewApp.js:88:7
    at C:\Users\Noam\AppData\Local\npm-cache\_npx\432d571bf15e5fbf\node_modules\cpr\lib\index.js:294:33
    at check (C:\Users\Noam\AppData\Local\npm-cache\_npx\432d571bf15e5fbf\node_modules\cpr\lib\index.js:190:17)
    at copy (C:\Users\Noam\AppData\Local\npm-cache\_npx\432d571bf15e5fbf\node_modules\cpr\lib\index.js:198:24)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Running the app (with `npm start`) gives:
```
🚨 Build Error

C:\Users\Noam\Desktop\Programs\Research 2022\contact-picker\Cargo.toml: Please install wasm-pack
```

EDIT: Trying to manually `cargo install wasm-pack` gives the following error message:

```
error: failed to run custom build command for `openssl-sys v0.9.74`

Caused by:
  process didn't exit successfully: `C:\Users\Noam\AppData\Local\Temp\cargo-installYTBdKh\release\build\openssl-sys-d97a6a84756b04f8\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  openssl-src: Enable the assembly language routines in building OpenSSL.
  running "perl" "./Configure" "--prefix=C:\\Users\\Noam\\AppData\\Local\\Temp\\cargo-installYTBdKh\\release\\build\\openssl-sys-69b856177b1e2088\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\Noam\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.21.0+1.1.1p\src\lib.rs:488:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.10.3`, intermediate artifacts can be found at `C:\Users\Noam\AppData\Local\Temp\cargo-installYTBdKh`
```

**Comment by lord-ne** [comment]
I was able to get `wasm-pack` to install by following the instructions here: https://github.com/sfackler/rust-openssl/issues/1086 (to install Perl). The app still won't run, I'll try `create-yew-app` again from scratch.

**Comment by lord-ne** [comment]
Working properly now

**Comment by liudonghua123** [comment]
I have this errors when execute `cargo install wasm-pack` on windows. I have installed [openssl](https://slproweb.com/download/Win64OpenSSL-3_1_1.exe) and configured environments (`set OPENSSL_DIR=D:/apps/OpenSSL-Win64 && set OPENSSL_STATIC=Yes`).

```
error: failed to run custom build command for `openssl-sys v0.9.88`

Caused by:
  process didn't exit successfully: `C:\Users\LIUD~1.H\AppData\Local\Temp\cargo-installIYO22f\release\build\openssl-sys-ddf320ebccccc120\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  openssl-src: Enable the assembly language routines in building OpenSSL.
  running "perl" "./Configure" "--prefix=C:\\Users\\LIUD~1.H\\AppData\\Local\\Temp\\cargo-installIYO22f\\release\\build\\openssl-sys-78a68fe1d0a571dc\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "VC-WIN64A"
  Configuring OpenSSL version 1.1.1u (0x1010115fL) for VC-WIN64A
  Using os-specific seed configuration

  --- stderr

  ******************************************************************************
  This perl implementation doesn't produce Windows like paths (with backward
  slash directory separators).  Please use an implementation that matches your
  building platform.

  This Perl version: 5.32.1 for x86_64-msys-thread-multi
  ******************************************************************************
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=C:\\Users\\LIUD~1.H\\AppData\\Local\\Temp\\cargo-installIYO22f\\release\\build\\openssl-sys-78a68fe1d0a571dc\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "VC-WIN64A"
      Exit status: exit code: 255


      ', C:\Users\Liu.D.H\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-111.26.0+1.1.1u\src\lib.rs:506:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.11.1`, intermediate artifacts can be found at `C:\Users\LIUD~1.H\AppData\Local\Temp\cargo-installIYO22f`

C:\Users\Liu.D.H>perl --version

This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-msys-thread-multi

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.


C:\Users\Liu.D.H>which perl
/c/msys64/usr/bin/perl

C:\Users\Liu.D.H>
```

It seems that I need to install windows perl instead of msys2 version of perl (`This perl implementation doesn't produce Windows like paths (with backward slash directory separators).  Please use an implementation that matches your building platform.`). So I installed [strawberry-perl](https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi).

And now it worked.

```
C:\Users\Liu.D.H>where perl
D:\apps\Strawberry\perl\bin\perl.exe
C:\msys64\usr\bin\perl.exe

C:\Users\Liu.D.H>echo %OPENSSL_DIR%
D:/apps/OpenSSL-Win64

C:\Users\Liu.D.H>cargo install wasm-pack
    Updating crates.io index
  Installing wasm-pack v0.11.1
......
   Compiling openssl v0.10.54
   Compiling vec_map v0.8.2
   Compiling encode_unicode v0.3.6
   Compiling rustc-demangle v0.1.23
   Compiling smallvec v1.10.0
   Compiling scopeguard v1.1.0
   Compiling console v0.15.7
   Compiling clap v2.34.0
   Compiling anstream v0.3.2
   Compiling foreign-types v0.3.2
   Compiling uuid v1.3.3
   Compiling tar v0.4.38
   Compiling same-file v1.0.6
   Compiling dirs-next v2.0.0
   Compiling hyper-tls v0.5.0
   Compiling structopt-derive v0.4.18
   Compiling toml v0.7.4
   Compiling url v2.4.0
   Compiling serde_urlencoded v0.7.1
   Compiling cargo-platform v0.1.2
   Compiling os_info v3.7.0
   Compiling openssl-macros v0.1.1
   Compiling time v0.1.45
   Compiling fs2 v0.4.3
   Compiling is_executable v0.1.2
   Compiling encoding_rs v0.8.32
   Compiling ipnet v2.7.2
   Compiling shell-words v1.1.0
   Compiling mime v0.3.17
   Compiling either v1.8.1
   Compiling zeroize v1.6.0
   Compiling hex v0.4.3
   Compiling base64 v0.21.2
   Compiling siphasher v0.3.10
   Compiling dialoguer v0.10.4
   Compiling which v4.4.0
   Compiling chrono v0.4.26
   Compiling reqwest v0.11.18
   Compiling human-panic v1.1.4
   Compiling cargo_metadata v0.15.4
   Compiling structopt v0.3.26
   Compiling walkdir v2.3.3
   Compiling parking_lot v0.12.1
   Compiling toml v0.5.11
   Compiling serde_ignored v0.1.7
   Compiling env_logger v0.10.0
   Compiling strsim v0.10.0
   Compiling glob v0.3.1
   Compiling bzip2 v0.4.4
   Compiling zstd v0.11.2+zstd.1.5.2
   Compiling zip v0.6.6
   Compiling binary-install v0.1.0
   Compiling wasm-pack v0.11.1
    Finished release [optimized] target(s) in 15m 13s
  Installing C:\Users\Liu.D.H\.cargo\bin\wasm-pack.exe
   Installed package `wasm-pack v0.11.1` (executable `wasm-pack.exe`)

C:\Users\Liu.D.H>

```
